"""
Django settings for instituo_caramelo project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Carrega as variáveis do arquivo .env (apenas para desenvolvimento local)
load_dotenv()

# Função auxiliar para ler booleanos de variáveis de ambientepip show python-dotenv


def get_bool_from_env(name, default=False):
    return os.environ.get(name, str(default)).lower() in ('true', '1', 't')
# -----------------------------------------------


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 1. SECRET_KEY: Lê do ambiente ou usa a chave forte gerada.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    '2b%2+zP!&w3N^hXy@m-q7sJ$fL9tA0vG#r4E5D8C1B6I(oU)p=vZa_cK0Lw2T'
)

# SECURITY WARNING: don't run with debug turned on in production!
# 2. DEBUG: Controlado pela variável de ambiente DEBUG (default=False em produção).
DEBUG = get_bool_from_env('DEBUG', default=False)

# 3. ALLOWED_HOSTS: Configuração para Render e Local
if DEBUG:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
else:
    # Hosts para produção (Render)
    RENDER_HOST = os.environ.get('RENDER_EXTERNAL_HOSTNAME')

    if RENDER_HOST:
        # Permite o subdomínio gratuito do Render
        ALLOWED_HOSTS = [RENDER_HOST]
    else:
        # Fallback de segurança
        ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', '')
        ALLOWED_HOSTS = ALLOWED_HOSTS_ENV.split(
            ',') if ALLOWED_HOSTS_ENV else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cadastro',
    'localflavor',
    'front',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Adicionado Whitenoise para servir arquivos estáticos em produção (Render)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'instituto_caramelo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'front', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'instituto_caramelo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# --- CONFIGURAÇÃO DO BANCO DE DADOS POSTGRESQL/RENDER ---
DATABASES = {
    # dj_database_url.config lê a variável de ambiente DATABASE_URL.
    # No Render, esta variável é fornecida pelo serviço de banco de dados.
    # Localmente, ela será lida do arquivo .env.
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL')
    )
}

# Fallback: Se a DATABASE_URL não for encontrada, retorna ao SQLite para testes de unidade
# ou se o .env não for carregado corretamente, embora o ideal seja garantir a DATABASE_URL.
if not DATABASES['default']:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
# -----------------------------------------------------


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'front', 'static'),
    os.path.join(BASE_DIR, 'front', 'assets'),
]

# Configuração de arquivos estáticos para Produção (WhiteNoise)
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'gabryellol123@gmail.com'
EMAIL_HOST_PASSWORD = 'knfe dtzs epso clvg'
DEFAULT_FROM_EMAIL = 'no-reply@institutocaramelo.com'
