# Generated by Django 5.2.8 on 2025-11-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=120, null=True)),
                ('representante', models.CharField(blank=True, max_length=150, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('motivacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('representante', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('motivacao', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
            ],
        ),
    ]
