# Generated by Django 5.2.8 on 2025-11-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_parceiro_ong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parceiro',
            name='ong',
        ),
    ]
