# Generated by Django 5.2.8 on 2025-11-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_parceiro_ong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('aprovado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='ong',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
