# Generated by Django 5.2.8 on 2025-11-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_cadastro_ong_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20),
        ),
    ]
